### ISSUE TITLE
Edit a Fire Lookout's fire environment 

### ISSUE THREAD

**Issue by emxsys** [emxsys/WorldWindWildfire#12]
- [ ] Select/override fuel model (See #55)
- [ ] Select/override fuel moisture scenario
- [ ] Edit/override wind speed and direction (See #54)
- [ ] Edit/override air temperature (See #54)
