### ISSUE TITLE
Fire Lookout expanded output

### ISSUE THREAD

**Issue by emxsys** [emxsys/WorldWindWildfire#2]
Display expanded details for the selected Fire Lookout in the output window.
- [ ] Wildfire Diamond
- [ ] Haul Chart (See #57)
- [ ] Fuel Moisture Scenario
- [ ] Fuel Model
- [ ] CPS Alignment of Forces (Wind/Slope/Solar Preheat)
- [ ] Solar Influence Air Temperature/Fuel Temperature/Fuel Moisture
- [ ] Fire Behavior Animation

@Dr-Eckleberg

**Comment by emxsys** [comment]
@Dr-Eckleberg I'm going to start working on the Haul Chart in the FireLookoutViewModel (in develop branch).  There's a place holder in this module for the WildfireDiamond.  Please feel free to flesh that out.

@zglueck I'm going to add a placeholder for a fire behavior animation. I would love your help.

**Comment by zglueck** [comment]
@emxsys absolutely! Just let me know what you are thinking.
