### ISSUE TITLE
Show Wildfire expanded output

### ISSUE THREAD

**Issue by emxsys** [emxsys/WorldWindWildfire#8]
- [x] Show date range with calendar/chart
- [x] Show percent contained with chart
- [x] Show textual details
- [x] Show size with a gauge (class breaks: Less than <10K; <25K; <50K; <100K; >=100K)
- [x] Show acreage in alternate units of measure (hectares, square miles)
